FROM alpine

LABEL MAINTAINER Greg White <grewhit25@gmail.com>

RUN set -x && \
		apk upgrade && \
		apk --no-cache add mpd && \
    rm -rf /var/lib/apt/lists/* /tmp/* && \
		mkdir /output && chown mpd:audio /output && \
		chown -R mpd:audio /var/lib/mpd


COPY mpd.conf /etc/mpd.conf

EXPOSE 6600

ENTRYPOINT ["mpd", "--stdout", "--no-daemon"]