FROM alpine

LABEL MAINTAINER Greg White <grewhit25@gmail.com>

RUN set -x && \
		apk upgrade && \
		apk --no-cache add mpd tini && \
    rm -rf /var/lib/apt/lists/* /tmp/* && \
		chown -R mpd:audio /var/lib/mpd && \
		mkdir /output && chown mpd:audio /output


COPY mpd.conf /etc/mpd.conf

# VOLUME [ "/output" ]
ENTRYPOINT [ "tini", "--"]
CMD ["mpd", "--stdout", "--no-daemon", "-v"]